Sprint 14
fatco321/java-shareit pull request #2
Opened 2022-10-30 16:30 UTC by fatco321

2022-10-31 09:41 UTC, kukolev requested changes

2022-10-31 09:41 UTC, kukolev commented on pom.xml
> +		<dependency>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-31 09:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (!booking.getItem().getAvailable()) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

Аналогично нужно поправить и в других подобных местах.

2022-10-31 09:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +    List<Item> findByNameContainsIgnoreCaseOrDescriptionContainsIgnoreCaseAndAvailableTrue(String name,
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-10-31 09:41 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public int hashCode() {
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-10-31 11:58 UTC, fatco321 commented on pom.xml
> +		<dependency>
В idea у меня корректно без tab-ов отображается.

2022-11-01 09:52 UTC, kukolev approved these changes

2022-11-25 15:06 UTC, merged